language: node_js

node_js:
  - 12

before_script:
  - npm ci

script:
  - npm run lint
  - npm test

after_success:
  - npm run test:coveralls

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - apisupport@zenvia.com
